### ISSUE TITLE
Helm chart alfresco-stable/alfresco-content-services@3.0.3 not working on Docker for Windows Desktop

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/acs-deployment#329] opened 2020-05-19 22:23 UTC
Neither of the postgres databases will start. It appears to be caused by this issue:

https://github.com/docker-library/postgres/issues/435

**Comment by binduwavell** [comment] 2020-05-19 22:30
Appears to also be an issue with version 4.0.3 of the helm chat. 

Here is sample log output showing the failure:
```
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".
Data page checksums are disabled.
fixing permissions on existing directory /var/lib/postgresql/data/pgdata ... ok
creating subdirectories ... ok
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default timezone ... Etc/UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
2020-05-19 22:25:00.461 UTC [79] FATAL:  data directory "/var/lib/postgresql/data/pgdata" has wrong ownership
2020-05-19 22:25:00.461 UTC [79] HINT:  The server must be started by the user that owns the data directory.
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/data/pgdata"
stream closed
```

**Comment by binduwavell** [comment] 2020-05-19 23:01
I will add I have 8 cores, 32G or RAM and 1G of swap allocated to Docker Desktop. And here is some version info:

```
λ docker --version
Docker version 19.03.4, build 9013bf5

λ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:39:02Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

λ helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

I also reduced the replica count from 2 to 1.

**Comment by nilsSure** [comment] 2021-03-04 14:20
I've got a fully working system using the steps from this page: [docker-desktop-deployment.md](https://github.com/Alfresco/acs-deployment/blob/master/docs/helm/docker-desktop-deployment.md). Below I have provided system info, tools versions, chart versions, pod statuses. Also did some quick tests like creating a site, adding/previewing/editing some content, search for content. Everything works as intended.

**System info**

```
PS C:\Users\aciubotaru> systeminfo

Host Name:                 aciubotaru-wind
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          N/A
Registered Organization:   N/A
Product ID:                00331-10000-00001-AA017
Original Install Date:     3/4/2021, 11:29:58 AM
System Boot Time:          3/4/2021, 11:57:22 AM
System Manufacturer:       Microsoft Corporation
System Model:              Virtual Machine
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 79 Stepping 1 GenuineIntel ~2295 Mhz
BIOS Version:              American Megatrends Inc. 090008 , 12/7/2018
Windows Directory:         C:\windows
System Directory:          C:\windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC) Coordinated Universal Time
Total Physical Memory:     32,768 MB
Available Physical Memory: 10,544 MB
Virtual Memory: Max Size:  37,888 MB
Virtual Memory: Available: 14,737 MB
Virtual Memory: In Use:    23,151 MB
Page File Location(s):     D:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\aciubotaru-wind
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB4601050
                           [02]: KB4580325
                           [03]: KB4598481
                           [04]: KB4601319
Network Card(s):           2 NIC(s) Installed.
                           [01]: Microsoft Hyper-V Network Adapter
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     168.63.129.16
                                 IP address(es)
                                 [01]: 10.0.0.4
                                 [02]: fe80::8549:f6ea:ae59:33d2
                           [02]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (WSL)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.18.176.1
                                 [02]: fe80::e92d:e17d:53c9:ab55
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

**Docker version**
```
PS C:\Users\aciubotaru> docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:14:16 2020
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Kubernetes version**
```
PS C:\Users\aciubotaru> kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Helm version**
```
PS C:\Users\aciubotaru> helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

**Helm chart version**
```
PS C:\Users\aciubotaru> helm list -n alfresco
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION
acs             alfresco        1               2021-03-04 12:49:10.6172373 +0000 UTC   deployed        alfresco-content-services-5.0.0-M2
acs-ingress     alfresco        1               2021-03-04 12:22:30.319078 +0000 UTC    deployed        ingress-nginx-3.7.1                     0.40.2
```

**Pods**
```
PS C:\Users\aciubotaru> kubectl get pods -n alfresco
NAME                                                   READY   STATUS    RESTARTS   AGE
acs-activemq-56756d5c8d-nnrwj                          1/1     Running   0          87m
acs-alfresco-cs-imagemagick-674966c55b-6jnjl           1/1     Running   0          87m
acs-alfresco-cs-libreoffice-7874444667-jwrr7           1/1     Running   2          87m
acs-alfresco-cs-pdfrenderer-96554844c-59nxp            1/1     Running   2          87m
acs-alfresco-cs-repository-769d66d45d-blmv6            1/1     Running   1          87m
acs-alfresco-cs-share-644559ff4-468j4                  1/1     Running   1          87m
acs-alfresco-cs-tika-6696d9886f-97mqv                  1/1     Running   0          87m
acs-alfresco-cs-transform-misc-68954f6cb5-84jsj        1/1     Running   1          87m
acs-alfresco-dw-67777dc68-ff72m                        1/1     Running   0          87m
acs-alfresco-filestore-978c8dcbc-hg5g4                 1/1     Running   0          87m
acs-alfresco-router-854964998-d25l6                    1/1     Running   0          87m
acs-alfresco-search-solr-5fbcd7c648-jrszl              1/1     Running   0          87m
acs-alfresco-sync-service-75fff4b9b-995zr              1/1     Running   0          87m
acs-ingress-ingress-nginx-controller-9d6d9df9c-v66jk   1/1     Running   0          114m
acs-postgresql-acs-0                                   1/1     Running   0          87m
acs-postgresql-syncservice-0                           1/1     Running   0          87m
```

**Comment by gavincornwell** [comment] 2021-03-04 16:45
As you can see from previous comment we have tested the latest milestone release with Docker for Desktop for Windows (thanks @nilsSure) as it seems to be working fine so I'm going to go ahead and close this issue.

**Closed by gavincornwell** 2021-03-04 16:45 UTC
Labels: triaged
