### ISSUE TITLE
GoogleDocs Error!

### ISSUE THREAD

**Issue by renatofritola** [Alfresco/acs-deployment#464] opened 2020-11-26 10:52 UTC
When starting Alfresco the following error with the GoogleDocs extension occurs:

``` log
2020-11-26 08:32:03,503  ERROR [management.subsystems.AbstractPropertyBackedBean] [localhost-startStop-1] Error auto-starting subsystem 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'googleDocsImportFormats' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/subsystems/googledocs/drive/google-customResponse-context.xml]: Cannot resolve reference to bean 'GoogleDocsService' while setting bean property 'googledocsService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'GoogleDocsService' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/subsystems/googledocs/drive/googledocs-context.xml]: Cannot resolve reference to bean 'googledocsService' while setting bean property 'target'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'googledocsService' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/subsystems/googledocs/drive/googledocs-context.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException
```

Version:

![image](https://user-images.githubusercontent.com/29155974/100342126-4bfa8b00-2fbc-11eb-93f4-d989bdfec2b5.png)

Full Log:

[alfresco-logs.log](https://github.com/Alfresco/acs-deployment/files/5602398/alfresco-logs.log)

**Comment by BladeRikWr** [comment] 2021-01-29 16:56
I'm having the same issue as well. This happens on a fresh Helm deployment, using the latest Chart version "5.0.0-M2", which deploys Alfresco Community version "7.0.0-A10".  
I followed this repo's EKS deployment doc to the dot, exception being that I used an AWS database instead of the PostgreSQL database included in the chart.

After I ran the `helm install acs alfresco/alfresco-content-services ...` command stated in the EKS deploy docs (the doc in this repo), everything launched ok. But as soon as I make a new site and try to create a new Google Doc, it gives the error "Couldn't connect to Google Docs". The repository logs are similar to renatofritola's logs, in that they show a bunch of `BeanCreationExceptions` caused by the Google Doc beans. 

So I thought, hm maybe it's because there is a version mismatch between the supported Google Doc subsystem and this Alfresco version. So I did a fresh deployment of Helm Chart version "5.0.0-M1" which deploys Alfresco Community version "6.2.1-A8". Again, I used an AWS database in place of the included one. Google Docs still doesn't work. Same errors show up in the logs. I'm almost at a loss for this.

**Comment by BladeRikWr** [comment] 2021-01-29 18:02
So in my Alfresco log [1], I noticed this:
```
Caused by: java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at org.alfresco.integrations.google.docs.service.GoogleDocsServiceImpl.init(GoogleDocsServiceImpl.java:344)
        ...
```
That last line led me to the [Alfresco Google Drive](https://github.com/Alfresco/googledrive) repo, specifically to the `GoogleDocsServiceImpl.java` file referenced in the error [(Link to that)](https://github.com/Alfresco/googledrive/blob/master/alfresco-googledrive-repo-base/src/main/java/org/alfresco/integrations/google/docs/service/GoogleDocsServiceImpl.java). Here is the offending method and line:

```
public void init() throws IOException
    {
        httpTransport = new NetHttpTransport();
        jsonFactory = new JacksonFactory();

        if (isBlank(clientSecret))
        {
   Line 344 --> clientSecrets = GoogleClientSecrets.load(jsonFactory, new InputStreamReader(
                GoogleDocsServiceImpl.class.getResourceAsStream("client_secret.json")));
        }
        else
        {
            clientSecrets = GoogleClientSecrets.load(jsonFactory, new StringReader(clientSecret));
        }
    }
```

Do I have to provide my own client Google OAuth secret? If so, where?

[1] [Alfresco.log](https://github.com/Alfresco/acs-deployment/files/5895442/Alfresco.log)

**Comment by gavincornwell** [comment] 2021-02-01 08:50
Hi @renatofritola and @BladeRikWr Thank you for reporting these issues. Unfortunately there does appear to be a problem with the GoogleDocs integration with the latest WIP version of Community, there is an issue on our internal backlog to address this.

You might have more luck if you go back to a previous version of community, however, if you do do this please bear in mind the comments I made here: https://github.com/Alfresco/acs-deployment/issues/489#issuecomment-766751200

**Comment by BladeRikWr** [comment] 2021-02-01 14:09
Thanks for the update Gavin! I'll try to wrangle together an older Alfresco installation.

**Comment by BladeRikWr** [comment] 2021-02-23 14:18
Just an update for future readers. I deployed Alfresco 6.2.0-ga (both Repository and Share), and Google Docs works on this stable version. 

You may be wondering, "but the main README says that the oldest Community version I can deploy is 6.2.1-A8!". Nonsense :)

Use the [community_values](https://github.com/Alfresco/acs-deployment/blob/v5.0.0-M1/helm/alfresco-content-services/community_values.yaml) file from tag `5.0.0-M1`. For the `alfresco/alfresco-content-repository-community` image, change its `tag` to use `6.2.0-ga`. For `alfresco/alfresco-share` image, change its `tag` to use `6.2.0`.

Also, if you're a Helm newbie like me, don't forget to use the previous Helm chart version when you get to the installation step:
```
helm install acs alfresco/alfresco-content-services \
--version="5.0.0-M1" \
...
```

**Comment by gavincornwell** [comment] 2021-03-02 15:39
This is being tracked internally via: https://alfresco.atlassian.net/browse/GOOGLEDOCS-501 and will be fixed in the forthcoming Community release. 

NOTE: The repo fix is also in the current alpha build being used on master, the Share counterpart will follow shortly.

**Comment by gavincornwell** [comment] 2021-03-15 14:16
This is now fixed with the latest Community docker compose file.

**Closed by gavincornwell** 2021-03-15 14:16 UTC
Labels: tracked, triaged
